package io.mattilsynet.design

// Generated by generateKotlinSources task. Do not edit manually.
object CssModules {
    private val map = mapOf<String, String>()
    fun resolve(vararg names: String): List<String> = names.toList()
    fun of(name: String): String = name
}
