name: Publish

on: 
  push:
    branches:
      - ci/publish-via-github-action # TODO endre dette tilbake til master
  workflow_dispatch:

jobs:
  build:
    name: "Build and publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version change
        id: check_version
        run: |
          if git diff HEAD^ HEAD -- package.json | grep '"version"'; then
            echo "Version changed, continuing."
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "Version not changed, skipping workflow."
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
          fi

      - uses: actions/setup-node@v4
        if: env.VERSION_CHANGED == 'true'
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        if: env.VERSION_CHANGED == 'true'
        run: npm i

      - name: Create a new Git tag
        if: env.VERSION_CHANGED == 'true'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Creating tag: $VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Publish to npm
        if: env.VERSION_CHANGED == 'true'
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Creating .npmrc
        if: env.VERSION_CHANGED == 'true'
        run: |
          cat << EOF > "$HOME/.npmrc"
            @mattilsynet:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GPR
        if: env.VERSION_CHANGED == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      